language: ruby
script: "script/test_all 2>&1"
bundler_args: "--standalone --binstubs"
before_install:
  # We need to ensure the latest version of Rubygems, unless we're on an old Ruby.
  - gem update --system $(ruby -e "puts '2.7.8' if ENV['RUBY_VERSION'] >= '2.3.0'")
  - gem update bundler
rvm:
  - 2.6.6
  - truffleruby-head
  - truffleruby

env:
  - RSPEC_BRANCH=master
  - RSPEC_BRANCH=2-99-maintenance
